name: E2E for Checkout Components

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-then-e2e:
    if: ${{ github.actor != 'renovate[bot]' && github.actor != 'lgtm-com[bot]' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.12.2]
        api-version: ["v68", "v69", "v70", "v71"]
        # node-version: [16.x, 18.x, 19.x]
        # Currently 18 and 19 are not supported, still keeping it
        # as a reminder for compatibility check
    steps:
    - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Project Dependencies
      run: yarn install
    - name: Build Project
      run: yarn build
    - name: Install Playwright Dependencies
      working-directory: packages/e2e-playwright/
      run: yarn install && npx playwright install --with-deps
    - name: Run stackhawk
       uses: stackhawk/hawkscan-action@v2.2.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
