name: Build and Scan test

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.12.2]
        api-version: ["v68", "v69", "v70", "v71"]
        # node-version: [16.x, 18.x, 19.x]
        # Currently 18 and 19 are not supported, still keeping it
        # as a reminder for compatibility check
    steps:
    - name: Install Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
